apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/external-dns/
