apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  labels:
    service: aws-load-balancer-controller
  annotations:
  namespace: kube-system
spec:
  releaseName: aws-load-balancer-controller

  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: aws-eks-charts
      chart: aws-load-balancer-controller
      version: ~x.x.x

  interval: 5m0s
  timeout: 5m0s
  values:
    clusterName: rohit-eks-1
    serviceAccount:
      create: false
      name: aws-load-balancer-controller
