apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-kafka

spec:
  # Secret names are always required.
  secretName: tls-kafka

  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  # secretTemplate:
  #   annotations:
  #     my-secret-annotation-1: "foo"
  #     my-secret-annotation-2: "bar"
  #   labels:
  #     my-secret-label: foo

  duration: 8760h # 90d
  renewBefore: 48h # 15d
  subject:
    organizations:
      - local
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: kafka.confluent.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - kafka.rohit.local
    - kafka.confluent.svc.cluster.local
    - kafka-2.kafka.confluent.svc.cluster.local
    - kafka-1.kafka.confluent.svc.cluster.local
    - kafka-0.kafka.confluent.svc.cluster.local
    - "*.kafka.rohit.local"
    - kafka.edge1.svc.cluster.local
    - kafka.hub1.svc.cluster.local
    - kafka.hub2.svc.cluster.local
    - "*.kafka.edge1.svc.cluster.local"
    - "*.kafka.hub1.svc.cluster.local"
    - "*.kafka.hub2.svc.cluster.local"
    - kafka
    - kraft.confluent.svc.cluster.local
    - kraft-2.kraft.confluent.svc.cluster.local
    - kraft-1.kraft.confluent.svc.cluster.local
    - kraft-0.kraft.confluent.svc.cluster.local
    - kraft

    # - www.example.com
  # uris:
  #   - spiffe://cluster.local/ns/sandbox/sa/example
  # ipAddresses:
  #   - 192.168.0.5
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer # vault-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
