apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: operators-level-0
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./cluster-resources/operators-level-0/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: aws-load-balancer-controller
      namespace: kube-system
