apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: operators-level-1
  namespace: flux-system
spec:
  interval: 0m3s
  path: ./cluster-resources/operators-level-1/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
