apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: operators-level-2
  namespace: flux-system
spec:
  dependsOn:
    - name: operators-level-1
  wait: true
  interval: 5m0s
  path: ./cluster-resources/operators-level-2/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
