apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: resources
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: operators-level-0
  wait: true
  path: ./cluster-resources/resources-operator-level-0/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
