apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: resources-operator-level-1
  namespace: flux-system
spec:
  interval: 0m3s
  dependsOn:
    - name: operators-level-1
  wait: true
  path: ./cluster-resources/resources-operator-level-1/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
