apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  labels:
    service: prometheus-operator
  annotations:
  namespace: monitoring
spec:
  values:
    ## Hosts is a valid FQDN
    prometheus:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: prometheus.${resource_prefix}.local
        hosts:
          - prometheus.${resource_prefix}.local
        tls:
          - secretName: prometheus-cert
            hosts:
              - prometheus.${resource_prefix}.local
        pathType: Prefix

    grafana:
      ingress:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: grafana.${resource_prefix}.local
        hosts:
          - grafana.${resource_prefix}.local
        tls:
          - secretName: grafana-cert
            hosts:
              - grafana.${resource_prefix}.local
