---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-operator
  namespace: keda
spec:
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: kedacore
      version: "2.*"
  interval: 5m0s
  timeout: 5m0s
  releaseName: keda
  values:
