apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-release.yaml
  - vault-init-job.yaml
patchesStrategicMerge:
  - vault-release-patch.yaml
  - vault-init-job-patch.yaml
