---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cfk-admin-binding
subjects:
  - kind: ServiceAccount
    name: confluent-for-kubernetes
    namespace: confluent
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
