apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cfk
  namespace: confluent
spec:
  # Secret names are always required.
  secretName: tls-cfk

  duration: 8760h # 90d
  renewBefore: 48h # 15d
  subject:
    organizations:
      - local
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: confluent-operator.confluent.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - confluent-operator.confluent.svc
    - confluent-operator.confluent.svc.cluster.local

    # - www.example.com
  # uris:
  #   - spiffe://cluster.local/ns/sandbox/sa/example
  # ipAddresses:
  #   - 192.168.0.5
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer # vault-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
