apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  labels:
    service: ingress-nginx
  annotations:
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx

  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      chart: ingress-nginx
      version: ~x.x.x

  interval: 5m0s
  timeout: 5m0s
  values:
    tcp:
      "2887": "confluent/zk-east-0-internal:2888"
      "2888": "confluent/zk-east-1-internal:2888"
      "2889": "confluent/zk-east-2-internal:2888"
      "2898": "confluent/zk-west-0-internal:2888"
      "2899": "confluent/zk-west-1-internal:2888"
    controller:
      extraArgs:
        enable-ssl-passthrough: "true"
      service:
        externalTrafficPolicy: "Local"
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
          service.beta.kubernetes.io/load-balancer-source-ranges: 10.0.0.0/16
