apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    server:
      extraEnvironmentVars:
        VAULT_SEAL_TYPE: awskms
        VAULT_AWSKMS_SEAL_KEY_ID: ${vault_auto_unseal_kms_id}
        AWS_REGION: ${aws_region}

      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: ${vault_role_arn}
    ui:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: vault.${resource_prefix}.local
