---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka2
  namespace: confluent
  labels:
    confluent-operator.webhooks.platform.confluent.io/disable: "true"
spec:
  replicas: 3
  oneReplicaPerNode: true
  podTemplate:
    resources:
      requests:
        memory: "6Gi"
        cpu: "1000m"

    serviceAccountName: kafka

  image:
    application: confluentinc/cp-server:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  dataVolumeCapacity: 100Gi
  configOverrides:
    # jvm:
    #   - -Djavax.net.ssl.trustStore=/usr/lib/jvm/jre/lib/security/cacerts
    #   - -Djavax.net.ssl.trustStorePassword=changeit
    log4j:
      - log4j.rootLogger=INFO, stdout
    server: #This config override is required for CP 7.0 update to use AclAuthorizer instead of SimpleAclAuthorizer
      # - authorizer.class.name=kafka.security.authorizer.AclAuthorizer
      - authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - confluent.tier.feature=true
      - confluent.tier.enable=true
      - confluent.tier.backend=S3
      - confluent.tier.s3.bucket=rohit-confluent
      - confluent.tier.s3.region=eu-west-2
      # - confluent.tier.s3.ssl.truststore.location=/usr/lib/jvm/java-11-amazon-corretto/lib/security/cacerts
      # - confluent.tier.s3.ssl.truststore.password=changeit
      # - confluent.tier.s3.ssl.truststore.type=JKS
      # - confluent.tier.sts.ssl.truststore.location=/usr/lib/jvm/java-11-amazon-corretto/lib/security/cacerts
      # - confluent.tier.sts.ssl.truststore.password=changeit
      # - confluent.tier.sts.ssl.truststore.type=JKS
      # - confluent.tier.s3.credentials.provider.class=WebIdentityTokenFileCredentialsProvider
  # confluent.tier.metadata.replication.factor=1
  tls:
    secretRef: tls-kafka
  listeners:
    internal:
      authentication:
        type: mtls
        principalMappingRules:
          - RULE:^CN=([a-zA-Z0-9]*).*$/$1/
      tls:
        enabled: true
        # Will use the certificates in the parent secretRef tls-kafka
    external:
      authentication:
        type: mtls
        principalMappingRules:
          - RULE:^CN=([a-zA-Z0-9]*).*$/$1/
      tls:
        enabled: true
        # Will use the certificates in the parent secretRef tls-kafka
      # externalAccess:
      #   type: loadBalancer
      #   loadBalancer:
      #     domain: kafka.rohit.local
      #     brokerPrefix: b
      #     bootstrapPrefix: kafka
      #     annotations:
      #       service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  authorization:
    type: simple
    superUsers:
      - User:kafka
  dependencies:
    kRaftController:
      controllerListener:
        tls:
          enabled: true
        authentication:
          type: mtls
      clusterRef:
        name: kraft
