apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  labels:
    service: metrics-server
  annotations:
  namespace: kube-system
spec:
  releaseName: metrics-server

  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      chart: metrics-server
      version: ~x.x.x

  interval: 5m0s
  timeout: 5m0s
  values:
    serviceMonitor:
      enabled: true
      additionalLabels:
        monitoring-platform: prometheus
