apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-elastic
  namespace: elastic-system
spec:
  # Secret names are always required.
  secretName: tls-elastic

  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  # secretTemplate:
  #   annotations:
  #     my-secret-annotation-1: "foo"
  #     my-secret-annotation-2: "bar"
  #   labels:
  #     my-secret-label: foo

  duration: 8760h # 90d
  renewBefore: 48h # 15d
  subject:
    organizations:
      - local
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: quickstart-es-http.elastic-system.es.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - quickstart-es-http.elastic-system.es.local
    - quickstart-es-http
    - quickstart-es-http.elastic-system.svc
    - quickstart-es-http.elastic-system
    - quickstart-es-internal-http.elastic-system.svc
    - quickstart-es-internal-http.elastic-system
    - "*.quickstart-es-default.elastic-system.svc"

    # - www.example.com
  # uris:
  #   - spiffe://cluster.local/ns/sandbox/sa/example
  # ipAddresses:
  #   - 192.168.0.5
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer # vault-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io

---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 8.8.1
  http:
    tls:
      certificate:
        secretName: tls-elastic

  nodeSets:
    - name: default
      count: 3
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 24Gi

          # cpu: 6000m
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 300Gi

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 8.8.1
  count: 1
  elasticsearchRef:
    name: quickstart
