---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: confluent
spec:
  chart:
    spec:
      chart: openldap-stack-ha
      sourceRef:
        kind: HelmRepository
        name: openldap
      version: "*.*"
  interval: 5m0s
  timeout: 5m0s
  releaseName: openldap
  values:
    global:
      ldapDomain: dc=cluster,dc=local
    replicaCount: 2
    logLevel: info
    users: kafka,connect,c3
    userPasswords: kafka,connect,c3
    replication:
      enabled: false
    persistence:
      enabled: false
    ltb-passwd:
      enabled: true
    phpldapadmin:
      enabled: false
