apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-kafka
  namespace: confluent
spec:
  # Secret names are always required.
  secretName: tls-kafka

  duration: 8760h # 90d
  renewBefore: 48h # 15d
  subject:
    organizations:
      - local
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: kafka.confluent.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - kafka-eu.confluent.svc.cluster.local
    - "*.kafka-eu.confluent.svc.cluster.local"
    - kafka-cn.confluent.svc.cluster.local
    - "*.kafka-cn.confluent.svc.cluster.local"
    - kafka-cn
    - kafka-eu

    - kraft-eu.confluent.svc.cluster.local
    - "*.kraft-eu.confluent.svc.cluster.local"
    - kraft-cn.confluent.svc.cluster.local
    - "*.kraft-cn.confluent.svc.cluster.local"
    - kraft-cn
    - kraft-eu

    - c3-eu.confluent.svc.cluster.local
    - c3-cn.confluent.svc.cluster.local
    - c3.eu.rohit.local
    - c3.cn.rohit.local
  # uris:
  #   - spiffe://cluster.local/ns/sandbox/sa/example
  # ipAddresses:
  #   - 192.168.0.5
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer # vault-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
