apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 3
  oneReplicaPerNode: true
  podTemplate:
    # serviceAccountName: zookeeper
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            confluent-platform: "true"

        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
  image:
    application: confluentinc/cp-zookeeper:7.3.3
    init: confluentinc/confluent-init-container:2.5.2
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  authentication:
    type: mtls
    principalMappingRules:
      - RULE:^CN=([a-zA-Z0-9]*).*$/$1/
  tls:
    secretRef: tls-zookeeper
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  oneReplicaPerNode: true
  podTemplate:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - kafka
                    - controlcenter
                    - perf-test-consumer
                    - perf-test-producer
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        memory: "25Gi"
        cpu: "1000m"
      limits:
        memory: "30Gi"
        cpu: "4000m"
    serviceAccountName: kafka
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            confluent-platform: "true"
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule

  image:
    application: confluentinc/cp-server:7.3.3
    init: confluentinc/confluent-init-container:2.5.2
  dataVolumeCapacity: 100Gi
  configOverrides:
    # jvm:
    #   - -Djavax.net.ssl.trustStore=/usr/lib/jvm/jre/lib/security/cacerts
    #   - -Djavax.net.ssl.trustStorePassword=changeit
    log4j:
      - log4j.rootLogger=TRACE, stdout
    server: #This config override is required for CP 7.0 update to use AclAuthorizer instead of SimpleAclAuthorizer
      - authorizer.class.name=kafka.security.authorizer.AclAuthorizer
      - confluent.tier.feature=true
      - confluent.tier.enable=true
      - confluent.tier.backend=S3
      - confluent.tier.s3.bucket=rohit-confluent
      - confluent.tier.s3.region=eu-west-2
      - confluent.tier.s3.ssl.truststore.location=/usr/lib/jvm/java-11-amazon-corretto/lib/security/cacerts
      - confluent.tier.s3.ssl.truststore.password=changeit
      - confluent.tier.s3.ssl.truststore.type=JKS
      - confluent.tier.sts.ssl.truststore.location=/usr/lib/jvm/java-11-amazon-corretto/lib/security/cacerts
      - confluent.tier.sts.ssl.truststore.password=changeit
      - confluent.tier.sts.ssl.truststore.type=JKS
      # - confluent.tier.s3.credentials.provider.class=WebIdentityTokenFileCredentialsProvider
  # confluent.tier.metadata.replication.factor=1
  tls:
    secretRef: tls-kafka
  listeners:
    internal:
      authentication:
        type: mtls
        principalMappingRules:
          - RULE:^CN=([a-zA-Z0-9]*).*$/$1/
      tls:
        enabled: true
        # Will use the certificates in the parent secretRef tls-kafka
    external:
      authentication:
        type: mtls
        principalMappingRules:
          - RULE:^CN=([a-zA-Z0-9]*).*$/$1/
      tls:
        enabled: true
        # Will use the certificates in the parent secretRef tls-kafka
      externalAccess:
        type: loadBalancer
        loadBalancer:
          domain: kafka.rohit.local
          brokerPrefix: b
          bootstrapPrefix: kafka
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  authorization:
    type: simple
    superUsers:
      - User:kafka
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2182
      authentication:
        type: mtls
      tls:
        enabled: true
  metrics:
    authentication:
      type: mtls
    tls:
      enabled: true
# ---
# apiVersion: platform.confluent.io/v1beta1
# kind: Connect
# metadata:
#   name: connect
#   namespace: confluent
# spec:
#   replicas: 2
#   image:
#     application: confluentinc/cp-server-connect:7.3.3
#     init: confluentinc/confluent-init-container:2.5.2
#   tls:
#     secretRef: tls-connect
#   externalAccess:
#     type: loadBalancer
#     loadBalancer:
#       domain: mydomain.example
#       prefix: connect
#   dependencies:
#     kafka:
#       bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
#       authentication:
#         type: mtls
#       tls:
#         enabled: true
# ---
# apiVersion: platform.confluent.io/v1beta1
# kind: SchemaRegistry
# metadata:
#   name: schemaregistry
#   namespace: confluent
# spec:
#   replicas: 1
#   image:
#     application: confluentinc/cp-schema-registry:7.3.3
#     init: confluentinc/confluent-init-container:2.5.2
#   tls:
#     secretRef: tls-schemaregistry
#   externalAccess:
#     type: loadBalancer
#     loadBalancer:
#       domain: mydomain.example
#       prefix: sr
#   dependencies:
#     kafka:
#       bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
#       authentication:
#         type: mtls
#       tls:
#         enabled: true
# ---
# apiVersion: platform.confluent.io/v1beta1
# kind: KsqlDB
# metadata:
#   name: ksqldb
#   namespace: confluent
# spec:
#   replicas: 2
#   image:
#     application: confluentinc/cp-ksqldb-server:7.3.3
#     init: confluentinc/confluent-init-container:2.5.2
#   dataVolumeCapacity: 10Gi
#   externalAccess:
#     type: loadBalancer
#     loadBalancer:
#       domain: mydomain.example
#       prefix: ksql
#   tls:
#     secretRef: tls-ksqldb
#   dependencies:
#     kafka:
#       bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
#       authentication:
#         type: mtls
#       tls:
#         enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  podTemplate:
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            confluent-platform: "true"
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
    probe:
      liveness:
        periodSeconds: 10
        failureThreshold: 5
        timeoutSeconds: 500
  image:
    application: confluentinc/cp-enterprise-control-center:7.3.3
    init: confluentinc/confluent-init-container:2.5.2
  dataVolumeCapacity: 10Gi
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: rohit.local
      prefix: controlcenter
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  # configOverrides:
  #   server:
  #     - confluent.controlcenter.mode.enable=management
  tls:
    secretRef: tls-c3
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
#     connect:
#       - name: connect
#         url:  https://connect.confluent.svc.cluster.local:8083
#         tls:
#           enabled: true
#     ksqldb:
#       - name: ksqldb
#         url:  https://ksqldb.confluent.svc.cluster.local:8088
#         tls:
#           enabled: true
#     schemaRegistry:
#       url: https://schemaregistry.confluent.svc.cluster.local:8081
#       tls:
#         enabled: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    release: prometheus-operator
    monitoring-platform: prometheus
  name: confluent
  namespace: confluent

spec:
  endpoints:
    - path: /
      port: prometheus
  namespaceSelector:
    matchNames:
      - confluent
  selector:
    matchLabels:
      confluent-platform: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  namespace: confluent
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::492737776546:role/rohit-confluent"
    eks.amazonaws.com/sts-regional-endpoints: "true"
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-sa-secret
  annotations:
    kubernetes.io/service-account.name: kafka
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-role
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-binding
subjects:
  - kind: ServiceAccount
    name: kafka
    namespace: confluent
roleRef:
  kind: ClusterRole
  name: kafka-role
  apiGroup: rbac.authorization.k8s.io
