apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: tenant-a-staging
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  values:
    replicaCount: 1
